version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: cloudquery-postgres
    environment:
      POSTGRES_DB: asset_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asset_inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

  embeddings:
    build:
      context: .
      dockerfile: Dockerfile.embeddings
    container_name: cloudquery-embeddings
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=asset_inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./generate_embeddings.py:/app/generate_embeddings.py
      - ./requirements.txt:/app/requirements.txt

volumes:
  postgres_data:
